oauth2:
  google:
    client-id: 618308615209-hc0oc3h414p8rhv1uou8lfmavmmod5b3.apps.googleusercontent.com    # REST API 키
    client-secret: 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
    scope: profile, email # 기본값이 openid, profile, email이지만 openid를 등록하게 되면 서비스마다(카카오, 네이버) OAuth2Service를 만들어야하기 때문에 profile, email만 scope로 지정
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
  kakao:
    client-id: 5739d24b3200adc30b4b7bce937f8352
    client-secret:  jf8ZHaFFc6p0NZCsmGHw60rP1brdpfbx
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: 클라이언트 ID
    client-secret: 클라이언트 SECRET
    redirect-uri: http://localhost:8080/login/oauth2/code/naver
    token-uri: https://nid.naver.com/oauth2.0/token
    resource-uri: https://openapi.naver.com/v1/nid/me

spring:
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tobemom
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #  show_sql: true
        format_sql: true
        use_sql_comments: true # sql 과 함께 jpql 주석처리되어  콘솔창에 출력

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWsdfadgdsflgsfgdsfgdsfgdfsgdsfgdfgNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400000 # 만료기간 1일


#jwt:
#  expiration_time: 86400000 # 만료기간 1일
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace 로그에 다음을 추가하기 org.hibernate.type : SQL 실행 파라미터를 로그로 남긴다.//이거대신 p6spy외부라이브러리가 더 깔끔함

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: ${key} # 노출되면 안됨!
